spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saline_royale?schema=public
    username: justinkatasi
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: postgresql
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate: DEBUG
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
